CREATE DATABASE IF NOT EXISTS HRETION;
USE HRETION;

-- CREATE TABLE USER
CREATE TABLE IF NOT EXISTS registerMainUser(
    ID_USER INT NOT NULL AUTO_INCREMENT,
    FULL_NAME VARCHAR(50) NOT NULL,
    NAME_HOTEL VARCHAR(50) NOT NULL,
    PHONE_NUMBER VARCHAR(15) NOT NULL,
    MAIL VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(ID_USER)
);

-- CREATE TABLE USERS 
CREATE TABLE IF NOT EXISTS USERS(
    ID_USER INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(20) NOT NULL,
    `PASSWORD` CHAR(255) NOT NULL,
    PRIMARY KEY(ID_USER),
    CONSTRAINT FK_ID_USER FOREIGN KEY (ID_USER)
    REFERENCES registerMainUser (ID_USER)
    ON DELETE CASCADE ON UPDATE CASCADE
);

